[tool.poetry]
name = "learn"
version = "0.1.0"
description = ""
authors = ["TOwInOK"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
result = "^0.17.0"
numpy = "^2.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
